<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260202133549 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, format VARCHAR(50) NOT NULL, course_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76591CC992 ON document (course_id)');
        $this->addSql('CREATE TABLE video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, file_name VARCHAR(255) DEFAULT NULL, url_externe VARCHAR(255) DEFAULT NULL, duree_en_secondes INT DEFAULT NULL, course_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC7DA2C591CC992 ON video (course_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_7CC7DA2C591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE response DROP CONSTRAINT fk_3e7b0bfbff6241a6');
        $this->addSql('DROP TABLE qcm');
        $this->addSql('DROP TABLE response');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE qcm (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(30) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE response (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(255) NOT NULL, answer VARCHAR(255) NOT NULL, qcm_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3e7b0bfbff6241a6 ON response (qcm_id)');
        $this->addSql('ALTER TABLE response ADD CONSTRAINT fk_3e7b0bfbff6241a6 FOREIGN KEY (qcm_id) REFERENCES qcm (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76591CC992');
        $this->addSql('ALTER TABLE video DROP CONSTRAINT FK_7CC7DA2C591CC992');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE video');
    }
}
